# Python 3.10-slim 버전
FROM python:3.10-slim

# 작업 디렉토리
WORKDIR /app

# requirements.txt 복사 및 설치
COPY requirements.txt .

# 컴파일이 필요한 패키지를 위해 gcc 설치
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
# 패키지 설치 
RUN pip install --no-cache-dir -r requirements.txt

# 소스 코드 복사
COPY . .

# 앱이 사용할 포트
EXPOSE 8000

# Uvicorn 실행 (main:app)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]